require: rubocop-rspec

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/NotToNot:
  EnforcedStyle: to_not

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - prawn-templates.gemspec
    - spec/**/*.rb
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

# We need to reference non-ascii characters when testing and explaining
# behavior related to win-1252, UTF-8 and UTF-16 encodings for example.
Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Encoding:
  EnforcedStyle: never

Style/FirstArrayElementLineBreak:
  Enabled: true

Style/FirstHashElementLineBreak:
  Enabled: true

Style/FirstMethodArgumentLineBreak:
  Enabled: true

Style/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/GuardClause:
  Enabled: false

# We don't always prefer modified if statements even if they do fit on
# a line.
Style/IfUnlessModifier:
  Enabled: false

Style/IndentArray:
  EnforcedStyle: consistent

Style/IndentHash:
  EnforcedStyle: consistent

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/MultilineOperationIndentation:
  EnforcedStyle: indented
  Exclude:
    - prawn-templates.gemspec

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '()'
    '%i': '[]'
    '%I': '[]'
    '%q': '()'
    '%Q': '()'
    '%r': '{}'
    '%s': '()'
    '%w': '[]'
    '%W': '[]'
    '%x': '()'

Style/SpaceAroundOperators:
  AllowForAlignment: false

Style/WhileUntilModifier:
  Enabled: false
